CREATE TABLE [Core].[Channel]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [ChannelId] UNIQUEIDENTIFIER NULL,
    [ChannelName] NVARCHAR(100) NOT NULL, 
    [ShouldListen] BIT NOT NULL DEFAULT 0, 
    [Data] NVARCHAR(MAX) NULL
)
GO

CREATE INDEX [IX_CHANNEL_CHANNELNAME] ON [Core].[Channel](ChannelName)