CREATE TABLE [Core].[Tags]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [TagId] UNIQUEIDENTIFIER NOT NULL, 
    [TagName] NVARCHAR(50) NOT NULL, 
    [Data] VARCHAR(MAX) NOT NULL
)
GO

CREATE INDEX [IX_TAGS_TAGID] ON [Core].[Tags](TagId)
GO

CREATE INDEX [IX_TAGS_TAGNAME] ON [Core].[Tags](TagName)
GO