CREATE TABLE [Core].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [Username] NVARCHAR(1000) NOT NULL, 
    [Email] NVARCHAR(1000) NOT NULL, 
    [Data] VARCHAR(MAX) NOT NULL
)
GO

CREATE UNIQUE INDEX [IX_USERS_USERID] ON [Core].[Users]([UserId])
GO
CREATE INDEX [IX_USERS_USERNAME] ON [Core].[Users]([Username])
GO
CREATE INDEX [IX_USERS_EMAIL] ON [Core].[Users]([Email])
GO